### ISSUE TITLE
dtc fails on rpi.dts in FreeBSD arm.GENERIC

### ISSUE THREAD

**Issue by emaste** [davidchisnall/dtc#13]
```
--- rpi.dtb ---
Generating rpi.dtb from rpi.dts
converting rpi.dts -> /scratch/tmp/emaste/obj/arm.armv6/scratch/tmp/emaste/freebsd/sys/GENERIC/modules/scratch/tmp/emaste/freebsd/sys/modules/dtb/rpi/rpi.dtb
Error on line 1214: Expected node name
  interrupt-affinity = <&{/cpus/cpu@0}>,
                         ^
Error on line 1214: Expected ; at end of property
  interrupt-affinity = <&{/cpus/cpu@0}>,
                         ^
Failed to parse tree.  Unhappy face!
*** [tegra124-jetson-tk1-fbsd.dtb] Error code 1
```

From [sys/gnu/dts/arm/tegra124.dtsi](https://svnweb.freebsd.org/base/head/sys/gnu/dts/arm/tegra124.dtsi?revision=306197&view=markup#l1139):
```
                interrupt-affinity = <&{/cpus/cpu@0}>,
                                     <&{/cpus/cpu@1}>,
                                     <&{/cpus/cpu@2}>,
                                     <&{/cpus/cpu@3}>;
```

**Comment by davidchisnall** [comment]
Please can you confirm that this is still the case with the latest dtc?  The 'Unhappy face' message was removed in 4d7c768386, quite a lot of changes ago.

**Comment by emaste** [comment]
Sorry about that, I thought the copy in FreeBSD had been updated to include these recent changes.

Indeed, after dropping dtc (at df5ede4) into my FreeBSD tree, the arm.GENERIC kernel built successfully in `make tinderbox.`
