### ISSUE TITLE
overlay support required

### ISSUE THREAD

**Issue by emaste** [davidchisnall/dtc#15]
As of FreeBSD r315031 (https://github.com/freebsd/freebsd/commit/37c58cdeac41f2860644462b24c9f613ff3702e1) FreeBSD tools pass -@ for FDT overlay.

**Comment by bsdimp** [comment]
Last time I checked, the BSDL dtc didn't support overlays...  But to be fair, it's a fairly new part of the standard....

**Comment by davidchisnall** [comment]
It doesn't, though the support needed from dtc is fairly small and shouldn't be too hard to add.

**Comment by bsdimp** [comment]
That would be awesome!

**Comment by davidchisnall** [comment]
If you could send a pull request with some simple test cases for overlay support, that would be very helpful.

**Comment by davidchisnall** [comment]
The last commit adds the `-@` option and generates a __symbols__ node when it's passed.  The docs that I found are quite sparse, so please can someone more familiar with overlays check that this is what's actually required?  Handling `/plugin/` is a little bit more complex, but shouldn't be too hard.

**Comment by davidchisnall** [comment]
Is there anything like a specification for the `__fixups__` and `__local_fixups__` sections?  GPL'd dtc doesn't appear to contain any documentation and the examples that I've found have two different formats for `__local_fixups__`.

**Comment by davidchisnall** [comment]
I believe that the last commit now includes everything required for overlay support, including generating plugins.  Please file more bugs (ideally with test cases) if it doesn't!
