### ISSUE TITLE
FreeBSD head -r320133 got: /usr/src/usr.bin/dtc/input_buffer.cc:658:2: error: 'result' does not name a type

### ISSUE THREAD

**Issue by markmi** [davidchisnall/dtc#17]
In input_buffer.cc

. . .
template<typename T>
struct divmod : public binary_operator<5, T>
{
       using binary_operator<5, T>::binary_operator;
       using binary_operator_base::result;
       result operator()() override
. . .

needs to have a "typename" added:

. . .
template<typename T>
struct divmod : public binary_operator<5, T>
{
       using binary_operator<5, T>::binary_operator;
       using typename binary_operator_base::result;
       result operator()() override
. . .

This was discovered by my attempt to build head -r320133
for powerpc64 via devel/powerpc64-xtoolchain-gcc (and
so devel/powerpc64-gcc, which is at 6.3.0 as I remember).
After reporting it on the lists I was asked to report it
upstream (here).

Adding the "typename" to the source I was building allowed
a rebuild to complete.

**Comment by davidchisnall** [comment]
Please can you send a pull request with your change?  This is probably only needed for gcc, but doesn't look harmful elsewhere.

**Comment by markmi** [comment]
I'm not familiar with making a pull request based on a
a local edit creating a difference from the svn revision.
So it may take me a while to figure out what to do.

The actual change is (via svnlite diff):

# svnlite diff /usr/src/usr.bin/dtc/input_buffer.cc
Index: /usr/src/usr.bin/dtc/input_buffer.cc
===================================================================
--- /usr/src/usr.bin/dtc/input_buffer.cc	(revision 320133)
+++ /usr/src/usr.bin/dtc/input_buffer.cc	(working copy)
@@ -654,7 +654,7 @@
 struct divmod : public binary_operator<5, T>
 {
 	using binary_operator<5, T>::binary_operator;
-	using binary_operator_base::result;
+	using typename binary_operator_base::result;
 	result operator()() override
 	{
 		result r = (*binary_operator_base::rhs)();

Although I'm not sure if spaces vs. tabs and such will
survive the E-mail use.

===
Mark Millard
markmi at dsl-only.net

On 2017-Jun-20, at 1:59 AM, davidchisnall <notifications@github.com> wrote:

Please can you send a pull request with your change? This is probably only needed for gcc, but doesn't look harmful elsewhere.

**Comment by markmi** [comment]
[Top post on what I did.]

I decided using git and github facilities more directly
would likely go smoother than involving svn(lite). But
still it is the first time for me to fork and do so.

I guessed that I should reference your master branch
for the pull request (instead of your upstream branch).

If I've screwed up anything in how I set up the pull
request, please let me know. Similarly if there are
conventions that I've violated even if they do not
technically prevent anything. I should learn as I
go.

===
Mark Millard
markmi at dsl-only.net

On 2017-Jun-20, at 2:10 AM, Mark Millard <markmi at dsl-only.net> wrote:

I'm not familiar with making a pull request based on a
a local edit creating a difference from the svn revision.
So it may take me a while to figure out what to do.

The actual change is (via svnlite diff):

# svnlite diff /usr/src/usr.bin/dtc/input_buffer.cc
Index: /usr/src/usr.bin/dtc/input_buffer.cc
===================================================================
--- /usr/src/usr.bin/dtc/input_buffer.cc	(revision 320133)
+++ /usr/src/usr.bin/dtc/input_buffer.cc	(working copy)
@@ -654,7 +654,7 @@
struct divmod : public binary_operator<5, T>
{
	using binary_operator<5, T>::binary_operator;
-	using binary_operator_base::result;
+	using typename binary_operator_base::result;
	result operator()() override
	{
		result r = (*binary_operator_base::rhs)();

Although I'm not sure if spaces vs. tabs and such will
survive the E-mail use.

===
Mark Millard
markmi at dsl-only.net

On 2017-Jun-20, at 1:59 AM, davidchisnall <notifications@github.com> wrote:

Please can you send a pull request with your change? This is probably only needed for gcc, but doesn't look harmful elsewhere.

**Comment by davidchisnall** [comment]
Thanks.
