### ISSUE TITLE
No incbin support

### ISSUE THREAD

**Issue by evadot** [davidchisnall/dtc#24]
GPL dtc have incbin directive that include a binary file
It's used by u-boot to generate image from .its file (FIT images) on aarch64.

**Comment by davidchisnall** [comment]
Is it documented somewhere?

**Comment by evadot** [comment]
I don't think so, at least I couldn't find any docs on it.

**Comment by davidchisnall** [comment]
Do you know what it does (is the binary just inserted as a property value, or is it parsed as a DTB?)

**Comment by evadot** [comment]
Just insert the binary it seems : 
`
$> dd if=/dev/random of=data.bin bs=1 count=8                                                                                                                                                       
8+0 records in
8+0 records out
8 bytes transferred in 0.000238 secs (33576 bytes/sec)
$> cat test.its                                                                                                                                                                                     
/dts-v1/;

/ {
        data = /incbin/("data.bin");
};
$> /usr/local/bin/dtc -I dts -O dtb -o test.itb < test.its
$> /usr/local/bin/dtc -I dtb -O dts < test.itb                                                                                                                                                      
/dts-v1/;

/ {
        data = <0x8b59170d 0xddb61bf8>;
};
`

**Comment by davidchisnall** [comment]
Can you mix it with other property values?  E.g. something like:

```
data = "foo", /incbin/("data.bin"), "bar";
```

It looks like it would be pretty easy to add.  Do the paths respect the include paths provided on the command line?

**Comment by evadot** [comment]
Mixing seems to work yes, that's the dts with your test : 

```
/dts-v1/;

/ {
        data = <0x666f6f00 0x8b59170d 0xddb61bf8 0x62617200>;
};
```

And yes include path specified by -i are respected.
