### ISSUE TITLE
incbin doesn't seems to work with u-boot-pine64

### ISSUE THREAD

**Issue by evadot** [davidchisnall/dtc#25]
When trying to compiling u-boot-pine64 with this DTC I have : 

./"board/sunxi/mksunxi_fit_atf.sh" \
arch/arm/dts/sun50i-a64-pine64.dtb arch/arm/dts/sun50i-a64-pine64-plus.dtb > u-boot.its
  MKIMAGE u-boot.itb
Error at u-boot.its:18:60: Cannot open binary include file
                        data = /incbin/("/usr/local/share/atf-allwinner/bl31.bin");
                                                                                 ^
Error at u-boot.its:18:60: Failed to find root node /.
                        data = /incbin/("/usr/local/share/atf-allwinner/bl31.bin");
                                                                                 ^
Failed to parse tree.
./tools/mkimage: Can't read u-boot.itb.tmp: Invalid argument

Obviously /usr/local/share/atf-allwinner/bl31.bin works and when setting dtc to the gpl dtc it works.

**Comment by davidchisnall** [comment]
I wonder if we're failing to correctly handle absolute paths?  I don't think that we have a test for that.

**Comment by davidchisnall** [comment]
Any chance of a test case for this?

**Comment by kevans91** [comment]
I seem to have goofed my cross-references, but this should be closed/fixed with the merge of PR #33, commit c3b8a2c
