### ISSUE TITLE
dtc(1) writes invalid /__local_fixups__ node

### ISSUE THREAD

**Issue by kevans91** [davidchisnall/dtc#27]
Our dtc(1) writes an invalid `/__local_fixups__` node, though I do like our consistent format better. =) Right now, we write a bunch of fix-up="path:name:offset" values, but it should be what looks like recreating the path structure to all nodes that need local fixups in the node. The libfdt reading code: https://github.com/dgibson/dtc/blob/master/libfdt/fdt_overlay.c#L231

Edited to add:

Precisely, this is the difference:

BSD dtc(1) [Incorrect]
```
	__local_fixups__ {

		fixup = "/fragment@1/__overlay__/foobar:foo:0";
		fixup = "/fragment@1/__overlay__/foobar:bar:0";
		fixup = "/fragment@1/__overlay__/foobar:foobar:0";
		fixup = "/fragment@1/__overlay__/foobar:foobar:4";
		fixup = "/fragment@1/__overlay__/foobar:foobar:12";
	};
```

GPL dtc(1) [Correct]
```
	__local_fixups__ {

		fragment@1 {

			__overlay__ {

				foobar {

					foo = <0x0>;
					bar = <0x0>;
					foobar = <0x0 0x4 0xc>;
				};
			};
		};
	};
```

The property values in `/__local_fixups__` describing the offsets that need fixups.

**Comment by kevans91** [comment]
Sorry, I meant to mention but was in a crunch for time- I'll look at fixing and submitting a pull request, rather than just leaving this vague issue. =)

**Comment by davidchisnall** [comment]
Ah, interesting.  The fixups spec is practically nonexistent, and I was going by descriptions from slides when I wrote this.  It shouldn't be too hard to construct nodes in a hierarchy like this.  If you could send a pull request with a test (input file and expected output), that would help a lot.

**Comment by kevans91** [comment]
Yeah, I noticed there was no spec for this. =( Anywho- I've added the test cases, split up amongst three to capture some of the more complex situations separately so it's easier to spot where things have gone wrong. I've no idea if I'll personally have the time to try implementing this; I noticed yesterday when I started looking at where to start that my C++ skills aren't what they used to be. =)

**Comment by davidchisnall** [comment]
Thanks, that should help.

**Comment by davidchisnall** [comment]
Should be fixed now.  I've tweaked the expected values from the tests because the order of `FOO` and `BAR` in the `__fixups__` section is different.  I also modified one of your expected values because it said `quz` instead of `qux` and source didn't include the string `quz`, so I don't know where that came from.  

@emaste This version probably wants importing to FreeBSD at some point.

**Comment by kevans91** [comment]
I'll test this and likely import to FreeBSD within the next couple of days, if neither of you have any objections to that timeline.

**Comment by emaste** [comment]
@kevans91 I'm fine with you handling the import in the next couple of days.

Note that we don't have this as vendor code in FreeBSD, it's just a straight copy and we generally do not have changes in the FreeBSD tree that are not here. That said, I see that pfg committed SPDX changes, have they made it here?

**Comment by davidchisnall** [comment]
No, I don't think so, and trying to merge from my git-svn branch is giving some merge conflicts because other people have done the dcommits and it's confused about history.

**Comment by kevans91** [comment]
I've submitted Pull Request #29 for SPDX additions
