### ISSUE TITLE
Parse /include/ from within a node

### ISSUE THREAD

**Issue by zxombie** [davidchisnall/dtc#4]
Some dts files have a `/include/` withing a node, e.g.:
```
/ {
  foo {
    compatible = "simple-bus";
    /include/ "bar.dtsi"
  };
};
```

An example of this from Linux is https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/boot/dts/amd/amd-seattle-soc.dtsi where the smb0 node includes amd-seattle-clks.dtsi.

**Comment by davidchisnall** [comment]
Is there any spec on where `/include/` is allowed?  It used to only be at the top level.  Presumably tokens can't be split between files, can they go anywhere aside from that?

**Comment by zxombie** [comment]
From reading the source of the gnu dtc they implement /include/ in the lexer so any time it sees the string it will parse the new file. I would guess they would accept it at any time, other than within another token.
