### ISSUE TITLE
dtb.cc needs to include stdlib.h

### ISSUE THREAD

**Issue by qemu-bsd-user** [davidchisnall/dtc#58]
dtb.cc uses exit(1). However, it doesn't include stdlib.h. Depending on what namespace pollution you have, this may or may not work by accident.

https://svnweb.freebsd.org/base?view=revision&revision=353961

fixes this. It's unclear to me the best way to submit this to you, so I'll start here but can shift to another method if you'd like.

Warner

**Comment by davidchisnall** [comment]
This was fixed by PR #62
