### ISSUE TITLE
Handle top level /delete-node/ directives

### ISSUE THREAD

**Issue by royger** [davidchisnall/dtc#64]
Hello,

It seems like DTC is not able to handle top level /delete-node/ directives:

converting /usr/src/sys/contrib/device-tree/src/arm64/rockchip/rk3326-odroid-go2.dts -> /usr/obj/usr/src/arm64.aarch64/sys/GENERIC/modules/usr/src/sys/modules/dtb/rockchip/rk3326-odroid-go2.dtb
Error at <standard input>:2260:1: Expected { to start new device tree node.

/delete-node/ &dsi_in_vopl;
 ^
Error at <standard input>:2260:12: Error parsing property.  Expected property value
/delete-node/ &dsi_in_vopl;
            ^
Failed to parse tree.
*** [rockchip/rk3326-odroid-go2.dtb] Error code 1

This is from rk3326-odroid-go2.dts which includes rk3326.dtsi that contains the offending directives.

**Comment by davidchisnall** [comment]
Please can you file a reduced test case?

**Comment by davidchisnall** [comment]
@royger ping?

**Comment by royger** [comment]
Sorry, let me see if I have some time for this, I really have no idea about dts.

**Comment by royger** [comment]
The example below seems to work for me using Linux DTC vs FreeBSD one:

```
/dts-v1/;

/ {
	test: node1 { };
};

/delete-node/ &test;
```
